// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nftug/wails-todo-app/infrastructure/config"
	"github.com/nftug/wails-todo-app/infrastructure/persistence"
	"github.com/nftug/wails-todo-app/infrastructure/todo"
	"github.com/nftug/wails-todo-app/presentation"
	"github.com/nftug/wails-todo-app/presentation/app"
	todo2 "github.com/nftug/wails-todo-app/usecase/todo"
)

// Injectors from wire.go:

func createAppRoot() *presentation.AppRoot {
	appApp := app.NewApp()
	greetApp := app.NewGreetApp()
	localPathService := config.NewLocalPathService()
	db := persistence.NewDB(localPathService)
	todoRepository := todo.NewTodoRepository(db)
	createTodoUseCase := todo2.NewCreateTodoUseCase(todoRepository)
	updateTodoUseCase := todo2.NewUpdateTodoUseCase(todoRepository)
	updateTodoStatusUseCase := todo2.NewUpdateTodoStatusUseCase(todoRepository)
	deleteTodoUseCase := todo2.NewDeleteTodoUseCase(todoRepository)
	todoQueryService := todo.NewTodoQueryService(db)
	getTodoUseCase := todo2.NewGetTodoUseCase(todoQueryService)
	getTodoListUseCase := todo2.NewGetTodoListUseCase(todoQueryService)
	todoApp := app.NewTodoApp(createTodoUseCase, updateTodoUseCase, updateTodoStatusUseCase, deleteTodoUseCase, getTodoUseCase, getTodoListUseCase)
	appRoot := presentation.NewAppRoot(appApp, greetApp, todoApp)
	return appRoot
}
