// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nftug/wails-todo-app/infrastructure/config"
	"github.com/nftug/wails-todo-app/infrastructure/persistence"
	"github.com/nftug/wails-todo-app/infrastructure/todo"
	"github.com/nftug/wails-todo-app/presentation"
	"github.com/nftug/wails-todo-app/presentation/app"
	"github.com/nftug/wails-todo-app/usecase"
	todo2 "github.com/nftug/wails-todo-app/usecase/todo"
)

// Injectors from wire.go:

func InitAppRoot() *presentation.AppRoot {
	localPathService := config.NewLocalPathService()
	db := persistence.NewDB(localPathService)
	todoRepository := todo.NewTodoRepository(db)
	createTodoUseCase := todo2.NewCreateTodoUseCase(todoRepository)
	updateTodoUseCase := todo2.NewUpdateTodoUseCase(todoRepository)
	updateTodoStatusUseCase := todo2.NewUpdateTodoStatusUseCase(todoRepository)
	deleteTodoUseCase := todo2.NewDeleteTodoUseCase(todoRepository)
	todoQueryService := todo.NewTodoQueryService(db)
	getTodoUseCase := todo2.NewGetTodoUseCase(todoQueryService)
	getTodoListUseCase := todo2.NewGetTodoListUseCase(todoQueryService)
	useCaseAdapter := usecase.NewUseCaseAdapter(createTodoUseCase, updateTodoUseCase, updateTodoStatusUseCase, deleteTodoUseCase, getTodoUseCase, getTodoListUseCase)
	todoApp := app.NewTodoApp(useCaseAdapter)
	appRoot := presentation.NewAppRoot(todoApp)
	return appRoot
}
