// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1) {
  return window['go']['app']['App']['CreateTodo'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ShowMessageDialog(arg1) {
  return window['go']['app']['App']['ShowMessageDialog'](arg1);
}
