// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['app']['TodoApp']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['app']['TodoApp']['Delete'](arg1);
}

export function GetDetails(arg1) {
  return window['go']['app']['TodoApp']['GetDetails'](arg1);
}

export function Search(arg1) {
  return window['go']['app']['TodoApp']['Search'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['app']['TodoApp']['Update'](arg1, arg2);
}

export function UpdateStatus(arg1, arg2) {
  return window['go']['app']['TodoApp']['UpdateStatus'](arg1, arg2);
}
