// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {todo} from '../models';
import {dtos} from '../models';

export function CreateTodo(arg1:todo.CreateCommand):Promise<dtos.CreatedResponse>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetTodoDetails(arg1:string):Promise<todo.DetailsResponse>;

export function GetTodoList(arg1:todo.Query):Promise<Array<todo.ItemResponse>>;

export function UpdateTodo(arg1:string,arg2:todo.UpdateCommand):Promise<void>;

export function UpdateTodoStatus(arg1:string,arg2:todo.UpdateStatusCommand):Promise<void>;
