// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {todo} from '../models';
import {interfaces} from '../models';

export function Create(arg1:todo.CreateCommand):Promise<interfaces.CreatedResponse>;

export function Delete(arg1:string):Promise<void>;

export function GetDetails(arg1:string):Promise<todo.DetailResponse>;

export function Search(arg1:todo.Query):Promise<Array<todo.ItemResponse>>;

export function Update(arg1:string,arg2:todo.UpdateCommand):Promise<void>;

export function UpdateStatus(arg1:string,arg2:todo.UpdateStatusCommand):Promise<void>;
