// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usecase

import (
	"github.com/nftug/wails-todo-app/infrastructure/persistence"
	"github.com/nftug/wails-todo-app/infrastructure/todo"
	todo2 "github.com/nftug/wails-todo-app/usecase/todo"
)

// Injectors from wire.go:

func InitUseCaseAdapterMock() *UseCaseAdapterMock {
	db := persistence.NewDBMock()
	todoRepository := todo.NewTodoRepository(db)
	createTodoUseCase := todo2.NewCreateTodoUseCase(todoRepository)
	updateTodoUseCase := todo2.NewUpdateTodoUseCase(todoRepository)
	updateTodoStatusUseCase := todo2.NewUpdateTodoStatusUseCase(todoRepository)
	deleteTodoUseCase := todo2.NewDeleteTodoUseCase(todoRepository)
	todoQueryService := todo.NewTodoQueryService(db)
	getTodoUseCase := todo2.NewGetTodoUseCase(todoQueryService)
	getTodoListUseCase := todo2.NewGetTodoListUseCase(todoQueryService)
	useCaseAdapter := NewUseCaseAdapter(createTodoUseCase, updateTodoUseCase, updateTodoStatusUseCase, deleteTodoUseCase, getTodoUseCase, getTodoListUseCase)
	useCaseAdapterMock := NewUseCaseAdapterMock(db, useCaseAdapter)
	return useCaseAdapterMock
}
