// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1) {
  return window['go']['app']['TodoApp']['CreateTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['app']['TodoApp']['DeleteTodo'](arg1);
}

export function GetTodoDetails(arg1) {
  return window['go']['app']['TodoApp']['GetTodoDetails'](arg1);
}

export function GetTodoList(arg1) {
  return window['go']['app']['TodoApp']['GetTodoList'](arg1);
}

export function UpdateTodo(arg1, arg2) {
  return window['go']['app']['TodoApp']['UpdateTodo'](arg1, arg2);
}

export function UpdateTodoStatus(arg1, arg2) {
  return window['go']['app']['TodoApp']['UpdateTodoStatus'](arg1, arg2);
}
