// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dialog} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ShowMessageDialog(arg1:dialog.DialogOptions):Promise<dialog.DialogButton>;
